In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import sys

# srcディレクトリをPythonの検索パスに追加
sys.path.append("/home/keiseki/JR_train_snow/30.src")
from utils.utils import plot_feature_vs_target


warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
df_train = pd.read_pickle("/home/keiseki/JR_train_snow/20.Data/train_time_weather.pkl")
df_test = pd.read_pickle("/home/keiseki/JR_train_snow/20.Data/test_time_weather.pkl")

In [3]:
df_train_winter = df_train[df_train["月"].isin([12,1,2,3])]
df_test_winter = df_test[df_test["月"].isin([12,1,2,3])]

In [4]:
df_train_winter.to_pickle("train_winter_only.pkl")
df_test_winter.to_pickle("test_winter_only.pkl")

In [5]:
df_train_winter = pd.read_pickle("/home/keiseki/JR_train_snow/20.Data/train_winter_only.pkl")

In [6]:
df_train.shape

(15339, 1769)

In [7]:
df_train_winter.shape

(4603, 1769)

In [8]:
import pandas as pd
import numpy as np


def analyze_snow_rate_by_temperature(
    df,
    temp_col,
    target_col,
    temp_bins=None
):
    """
    気温帯ごとの着雪発生率を集計する。

    Parameters
    ----------
    df : pandas.DataFrame
        分析対象データ
    temp_col : str
        気温の列名
    target_col : str
        目的変数の列名
    temp_bins : list or None
        気温帯の境界。
        Noneの場合は1℃刻み。

    Returns
    -------
    summary : pandas.DataFrame
        気温帯ごとの件数・着雪発生件数・発生率など
    """

    data = df[[temp_col, target_col]].copy()

    # 数値化
    data[temp_col] = pd.to_numeric(
        data[temp_col],
        errors="coerce"
    )

    data[target_col] = pd.to_numeric(
        data[target_col],
        errors="coerce"
    )

    # 欠損除外
    data = data.dropna()

    # 気温帯を指定
    if temp_bins is None:
        temp_min = np.floor(data[temp_col].min())
        temp_max = np.ceil(data[temp_col].max())

        temp_bins = np.arange(
            temp_min,
            temp_max + 1,
            1
        )

    data["気温帯"] = pd.cut(
        data[temp_col],
        bins=temp_bins,
        right=False
    )

    # 着雪発生フラグ
    data["着雪発生"] = data[target_col] > 0

    # 集計
    summary = data.groupby(
        "気温帯",
        observed=True
    ).agg(
        件数=("着雪発生", "size"),
        着雪発生件数=("着雪発生", "sum"),
        平均着雪量=(target_col, "mean"),
        最大着雪量=(target_col, "max")
    )

    # 発生率
    summary["着雪発生率"] = (
        summary["着雪発生件数"]
        / summary["件数"]
        * 100
    )

    return summary

In [9]:
for col in df_train.columns:
    if "気温" in col:
        print(f"--- {col} ---")

        summary = analyze_snow_rate_by_temperature(
            df_train,
            temp_col=col,
            target_col="合計"
        )

        display(summary)

--- 富山_気温_℃__1_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-2.0, -1.0)  178       6  0.000200  0.018895   3.370787
[-1.0, 0.0)   354       5  0.000076  0.020128   1.412429
[0.0, 1.0)    362      52  0.000775  0.023197  14.364641
[1.0, 2.0)    575      18  0.000045  0.003791   3.130435
[2.0, 3.0)    440       0  0.000000  0.000000   0.000000
[3.0, 4.0)    572       0  0.000000  0.000000   0.000000
[4.0, 5.0)    312      27  0.000187  0.015786   8.653846
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    484       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)     88       0  0.000000  0.000000   0.000000
[9.0, 10.0)    88       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__2_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-2.0, -1.0)  178       5  0.000033  0.003999   2.808989
[-1.0, 0.0)   354       6  0.000160  0.020128   1.694915
[0.0, 1.0)    541      70  0.000567  0.023197  12.939002
[1.0, 2.0)    352       0  0.000000  0.000000   0.000000
[2.0, 3.0)    532      27  0.000110  0.015786   5.075188
[3.0, 4.0)    660       0  0.000000  0.000000   0.000000
[4.0, 5.0)    264       0  0.000000  0.000000   0.000000
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)     88       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__3_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-3.0, -2.0)   44       0  0.000000  0.000000   0.000000
[-2.0, -1.0)  134       5  0.000044  0.003999   3.731343
[-1.0, 0.0)   398       6  0.000142  0.020128   1.507538
[0.0, 1.0)    497      70  0.000617  0.023197  14.084507
[1.0, 2.0)    488      27  0.000120  0.015786   5.532787
[2.0, 3.0)    440       0  0.000000  0.000000   0.000000
[3.0, 4.0)    528       0  0.000000  0.000000   0.000000
[4.0, 5.0)    352       0  0.000000  0.000000   0.000000
[5.0, 6.0)    220       0  0.000000  0.000000   0.000000
[6.0, 7.0)    440       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)     88       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__4_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-3.0, -2.0)   44       0  0.000000  0.000000   0.000000
[-2.0, -1.0)  178       5  0.000033  0.003999   2.808989
[-1.0, 0.0)   354       6  0.000160  0.020128   1.694915
[0.0, 1.0)    541      70  0.000567  0.023197  12.939002
[1.0, 2.0)    488      27  0.000120  0.015786   5.532787
[2.0, 3.0)    572       0  0.000000  0.000000   0.000000
[3.0, 4.0)    484       0  0.000000  0.000000   0.000000
[4.0, 5.0)    308       0  0.000000  0.000000   0.000000
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    132       0  0.000000  0.000000   0.000000
[9.0, 10.0)    44       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__5_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-3.0, -2.0)   44       0  0.000000  0.000000   0.000000
[-2.0, -1.0)  222       5  0.000027  0.003999   2.252252
[-1.0, 0.0)   317      45  0.000947  0.023197  14.195584
[0.0, 1.0)    668      57  0.000179  0.020128   8.532934
[1.0, 2.0)    486       1  0.000003  0.001653   0.205761
[2.0, 3.0)    484       0  0.000000  0.000000   0.000000
[3.0, 4.0)    616       0  0.000000  0.000000   0.000000
[4.0, 5.0)    176       0  0.000000  0.000000   0.000000
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)     44       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)    44       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__6_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   94      25  0.003838  0.049420  26.595745
[-2.0, -1.0)  222       9  0.000183  0.018895   4.054054
[-1.0, 0.0)   176       0  0.000000  0.000000   0.000000
[0.0, 1.0)    809      98  0.000476  0.023197  12.113721
[1.0, 2.0)    440       0  0.000000  0.000000   0.000000
[2.0, 3.0)    574       1  0.000003  0.001653   0.174216
[3.0, 4.0)    484       0  0.000000  0.000000   0.000000
[4.0, 5.0)    264       0  0.000000  0.000000   0.000000
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)    176       0  0.000000  0.000000   0.000000
[7.0, 8.0)    132       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)    88       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__7_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   94      25  0.003838  0.049420  26.595745
[-2.0, -1.0)  187      47  0.001611  0.023197  25.133690
[-1.0, 0.0)   352       4  0.000029  0.005348   1.136364
[0.0, 1.0)    492      56  0.000233  0.020128  11.382114
[1.0, 2.0)    396       0  0.000000  0.000000   0.000000
[2.0, 3.0)    618       1  0.000003  0.001653   0.161812
[3.0, 4.0)    660       0  0.000000  0.000000   0.000000
[4.0, 5.0)    176       0  0.000000  0.000000   0.000000
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    176       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)    88       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)  132       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__8_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)  147      66  0.004260  0.049420  44.897959
[-1.0, 0.0)   222       9  0.000183  0.018895   4.054054
[0.0, 1.0)    536      56  0.000186  0.015786  10.447761
[1.0, 2.0)    572       1  0.000035  0.020128   0.174825
[2.0, 3.0)    354       1  0.000005  0.001653   0.282486
[3.0, 4.0)    440       0  0.000000  0.000000   0.000000
[4.0, 5.0)    396       0  0.000000  0.000000   0.000000
[5.0, 6.0)    352       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__9_00 ---

               件数  着雪発生件数    平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)   103      66  0.00608  0.049420  64.077670
[0.0, 1.0)    402      37  0.00026  0.018895   9.203980
[1.0, 2.0)    578      30  0.00010  0.020128   5.190311
[2.0, 3.0)    352       0  0.00000  0.000000   0.000000
[3.0, 4.0)    440       0  0.00000  0.000000   0.000000
[4.0, 5.0)    264       0  0.00000  0.000000   0.000000
[5.0, 6.0)    264       0  0.00000  0.000000   0.000000
[6.0, 7.0)    528       0  0.00000  0.000000   0.000000
[7.0, 8.0)    264       0  0.00000  0.000000   0.000000
[8.0, 9.0)    528       0  0.00000  0.000000   0.000000
[9.0, 10.0)    88       0  0.00000  0.000000   0.000000
[10.0, 11.0)  132       0  0.00000  0.000000   0.000000
[11.0, 12.0)  176       0  0.00000  0.000000   0.000000
[12.0, 13.0)   88       0  0.00000  0.000000   0.000000
[13.0, 14.0)   44       0  0.00000  0.000000   0.000000
[14.0, 15.0)   88       0  0.00000  0.000000   0.000000
[15.0, 16.0)   88       0  0.00000  0.000000   0.000000
[16.0, 17.0)   88       0  0.00000  0.000000   0.000000
[17.0, 18.0)   44       0  0.00000  0.000000   0.000000
[18.0, 19.0)   44       0  0.00000  0.000000   0.000000

--- 富山_気温_℃__10_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)  103      66  0.006080  0.049420  64.077670
[0.0, 1.0)    268      35  0.000282  0.018895  13.059701
[1.0, 2.0)    358      30  0.000181  0.015786   8.379888
[2.0, 3.0)    266       1  0.000006  0.001653   0.375940
[3.0, 4.0)    660       1  0.000030  0.020128   0.151515
[4.0, 5.0)    176       0  0.000000  0.000000   0.000000
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    484       0  0.000000  0.000000   0.000000
[7.0, 8.0)    352       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)  132       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__11_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    94      29  0.004207  0.049420  30.851064
[0.0, 1.0)    136      27  0.000429  0.015786  19.852941
[1.0, 2.0)    400      31  0.000102  0.003999   7.750000
[2.0, 3.0)    178       2  0.000039  0.005348   1.123596
[3.0, 4.0)    222       2  0.000004  0.000524   0.900901
[4.0, 5.0)    396       1  0.000051  0.020128   0.252525
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)  176       0  0.000000  0.000000   0.000000
[16.0, 17.0)  176       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[19.0, 20.0)   88       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__12_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    92      31  0.001013  0.018895  33.695652
[0.0, 1.0)     94      25  0.003838  0.049420  26.595745
[1.0, 2.0)    267      21  0.000116  0.003999   7.865169
[2.0, 3.0)    178       1  0.000009  0.001653   0.561798
[3.0, 4.0)    355      12  0.000030  0.002210   3.380282
[4.0, 5.0)    264       2  0.000096  0.020128   0.757576
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    352       0  0.000000  0.000000   0.000000
[7.0, 8.0)    528       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  308       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[15.0, 16.0)  176       0  0.000000  0.000000   0.000000
[16.0, 17.0)  176       0  0.000000  0.000000   0.000000
[18.0, 19.0)  132       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__13_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    92      31  0.001013  0.018895  33.695652
[0.0, 1.0)     88       0  0.000000  0.000000   0.000000
[1.0, 2.0)    138      28  0.002650  0.049420  20.289855
[2.0, 3.0)    223      19  0.000141  0.005348   8.520179
[3.0, 4.0)    533      13  0.000023  0.002210   2.439024
[4.0, 5.0)    132       1  0.000152  0.020128   0.757576
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    132       0  0.000000  0.000000   0.000000
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    440       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)  308       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)  220       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[19.0, 20.0)  132       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[22.0, 23.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__14_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    48      27  0.001216  0.015786  56.250000
[0.0, 1.0)     88       4  0.000395  0.018895   4.545455
[1.0, 2.0)    182      28  0.002009  0.049420  15.384615
[2.0, 3.0)    179      18  0.000146  0.003791  10.055866
[3.0, 4.0)    533      14  0.000033  0.005348   2.626642
[4.0, 5.0)    176       1  0.000114  0.020128   0.568182
[5.0, 6.0)    132       0  0.000000  0.000000   0.000000
[6.0, 7.0)    352       0  0.000000  0.000000   0.000000
[7.0, 8.0)    484       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   484       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[15.0, 16.0)  176       0  0.000000  0.000000   0.000000
[16.0, 17.0)  132       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   88       0  0.000000  0.000000   0.000000
[19.0, 20.0)  132       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__15_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    48      27  0.001216  0.015786  56.250000
[0.0, 1.0)     44       0  0.000000  0.000000   0.000000
[1.0, 2.0)    270      32  0.001483  0.049420  11.851852
[2.0, 3.0)    176       0  0.000000  0.000000   0.000000
[3.0, 4.0)    448      32  0.000098  0.005348   7.142857
[4.0, 5.0)    220       1  0.000091  0.020128   0.454545
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    352       0  0.000000  0.000000   0.000000
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    132       0  0.000000  0.000000   0.000000
[9.0, 10.0)   484       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)  264       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)  308       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[19.0, 20.0)   88       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__16_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    48      27  0.001216  0.015786  56.250000
[0.0, 1.0)     88       4  0.000395  0.018895   4.545455
[1.0, 2.0)     94      25  0.003838  0.049420  26.595745
[2.0, 3.0)    399      21  0.000078  0.003999   5.263158
[3.0, 4.0)    443      12  0.000038  0.005348   2.708804
[4.0, 5.0)    178       2  0.000005  0.000524   1.123596
[5.0, 6.0)    308       1  0.000065  0.020128   0.324675
[6.0, 7.0)    440       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   484       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)  308       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[15.0, 16.0)  176       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[20.0, 21.0)   88       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__17_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    48      27  0.001216  0.015786  56.250000
[0.0, 1.0)    135      22  0.000451  0.018895  16.296296
[1.0, 2.0)    182      28  0.002009  0.049420  15.384615
[2.0, 3.0)    531      13  0.000030  0.005348   2.448211
[3.0, 4.0)    354       1  0.000005  0.001653   0.282486
[4.0, 5.0)    132       0  0.000000  0.000000   0.000000
[5.0, 6.0)    528       1  0.000038  0.020128   0.189394
[6.0, 7.0)    352       0  0.000000  0.000000   0.000000
[7.0, 8.0)    352       0  0.000000  0.000000   0.000000
[8.0, 9.0)    440       0  0.000000  0.000000   0.000000
[9.0, 10.0)   308       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)  220       0  0.000000  0.000000   0.000000
[15.0, 16.0)  176       0  0.000000  0.000000   0.000000
[20.0, 21.0)   88       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__18_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    48      27  0.001216  0.015786  56.250000
[0.0, 1.0)    229      47  0.001841  0.049420  20.524017
[1.0, 2.0)    398       5  0.000015  0.003999   1.256281
[2.0, 3.0)    353      11  0.000043  0.005348   3.116147
[3.0, 4.0)    352       0  0.000000  0.000000   0.000000
[4.0, 5.0)    222       2  0.000098  0.020128   0.900901
[5.0, 6.0)    484       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    528       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)    88       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)  264       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__19_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    48      27  0.001216  0.015786  56.250000
[0.0, 1.0)    229      50  0.001863  0.049420  21.834061
[1.0, 2.0)    487      12  0.000022  0.002210   2.464066
[2.0, 3.0)    398       2  0.000018  0.005348   0.502513
[3.0, 4.0)    484       1  0.000042  0.020128   0.206612
[4.0, 5.0)    264       0  0.000000  0.000000   0.000000
[5.0, 6.0)    616       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    484       0  0.000000  0.000000   0.000000
[8.0, 9.0)    220       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__20_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)  101      68  0.003207  0.023197  67.326733
[-1.0, 0.0)   138      32  0.002902  0.049420  23.188406
[0.0, 1.0)    223      18  0.000117  0.003791   8.071749
[1.0, 2.0)    443      13  0.000036  0.005348   2.934537
[2.0, 3.0)    530       2  0.000041  0.020128   0.377358
[3.0, 4.0)    396       0  0.000000  0.000000   0.000000
[4.0, 5.0)    484       0  0.000000  0.000000   0.000000
[5.0, 6.0)    440       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__21_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)   230      59  0.001995  0.049420  25.652174
[0.0, 1.0)    269      20  0.000101  0.003791   7.434944
[1.0, 2.0)    443      12  0.000038  0.005348   2.708804
[2.0, 3.0)    528       1  0.000038  0.020128   0.189394
[3.0, 4.0)    440       0  0.000000  0.000000   0.000000
[4.0, 5.0)    572       0  0.000000  0.000000   0.000000
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__22_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   53      41  0.005010  0.023197  77.358491
[-2.0, -1.0)  142      55  0.002987  0.049420  38.732394
[-1.0, 0.0)   220       4  0.000158  0.018895   1.818182
[0.0, 1.0)    356       4  0.000022  0.005348   1.123596
[1.0, 2.0)    312      28  0.000115  0.003791   8.974359
[2.0, 3.0)    660       1  0.000030  0.020128   0.151515
[3.0, 4.0)    484       0  0.000000  0.000000   0.000000
[4.0, 5.0)    440       0  0.000000  0.000000   0.000000
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)     88       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__23_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   53      41  0.005010  0.023197  77.358491
[-2.0, -1.0)   92      30  0.000689  0.015786  32.608696
[-1.0, 0.0)   270      29  0.001465  0.049420  10.740741
[0.0, 1.0)    533      14  0.000033  0.005348   2.626642
[1.0, 2.0)    355      18  0.000074  0.003791   5.070423
[2.0, 3.0)    616       1  0.000033  0.020128   0.162338
[3.0, 4.0)    440       0  0.000000  0.000000   0.000000
[4.0, 5.0)    484       0  0.000000  0.000000   0.000000
[5.0, 6.0)    176       0  0.000000  0.000000   0.000000
[6.0, 7.0)    352       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000

--- 富山_気温_℃__0_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-2.0, -1.0)  180       3  0.000014  0.001653   1.666667
[-1.0, 0.0)   308       8  0.000194  0.020128   2.597403
[0.0, 1.0)    406      52  0.000691  0.023197  12.807882
[1.0, 2.0)    399      18  0.000065  0.003791   4.511278
[2.0, 3.0)    616       0  0.000000  0.000000   0.000000
[3.0, 4.0)    352       0  0.000000  0.000000   0.000000
[4.0, 5.0)    484       0  0.000000  0.000000   0.000000
[5.0, 6.0)    312      27  0.000187  0.015786   8.653846
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    352       0  0.000000  0.000000   0.000000
[8.0, 9.0)    132       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__1_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)  138      26  0.002760  0.049420  18.840580
[-1.0, 0.0)    44       0  0.000000  0.000000   0.000000
[0.0, 1.0)    544      66  0.000605  0.023197  12.132353
[1.0, 2.0)    441      13  0.000033  0.003999   2.947846
[2.0, 3.0)    616       0  0.000000  0.000000   0.000000
[3.0, 4.0)    440       1  0.000012  0.005348   0.227273
[4.0, 5.0)    576      27  0.000101  0.015786   4.687500
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    176       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)   44       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__2_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   88       1  0.000229  0.020128   1.136364
[-1.0, 0.0)   182      25  0.001982  0.049420  13.736264
[0.0, 1.0)    454      61  0.000644  0.023197  13.436123
[1.0, 2.0)    443      18  0.000115  0.018895   4.063205
[2.0, 3.0)    572       0  0.000000  0.000000   0.000000
[3.0, 4.0)    484       1  0.000011  0.005348   0.206612
[4.0, 5.0)    664      27  0.000088  0.015786   4.066265
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)     88       0  0.000000  0.000000   0.000000
[7.0, 8.0)    352       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__3_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   44       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   226      25  0.001596  0.049420  11.061947
[0.0, 1.0)    588      63  0.000535  0.023197  10.714286
[1.0, 2.0)    485      17  0.000102  0.018895   3.505155
[2.0, 3.0)    396       0  0.000000  0.000000   0.000000
[3.0, 4.0)    488      28  0.000131  0.015786   5.737705
[4.0, 5.0)    660       0  0.000000  0.000000   0.000000
[5.0, 6.0)    440       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)    132       0  0.000000  0.000000   0.000000
[9.0, 10.0)   132       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__4_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   44       0  0.000000  0.000000   0.000000
[-2.0, -1.0)   50      25  0.007215  0.049420  50.000000
[-1.0, 0.0)   132       0  0.000000  0.000000   0.000000
[0.0, 1.0)    534      31  0.000107  0.020128   5.805243
[1.0, 2.0)    581      48  0.000525  0.023197   8.261618
[2.0, 3.0)    574       2  0.000012  0.005348   0.348432
[3.0, 4.0)    484       0  0.000000  0.000000   0.000000
[4.0, 5.0)    576      27  0.000101  0.015786   4.687500
[5.0, 6.0)    220       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    176       0  0.000000  0.000000   0.000000
[8.0, 9.0)    220       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__5_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   44       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   272      28  0.001404  0.049420  10.294118
[0.0, 1.0)    584      63  0.000559  0.023197  10.787671
[1.0, 2.0)    441      13  0.000033  0.003999   2.947846
[2.0, 3.0)    484       0  0.000000  0.000000   0.000000
[3.0, 4.0)    402      29  0.000163  0.015786   7.213930
[4.0, 5.0)    660       0  0.000000  0.000000   0.000000
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    132       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__6_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   44       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   228      27  0.001586  0.049420  11.842105
[0.0, 1.0)    440       7  0.000090  0.018895   1.590909
[1.0, 2.0)    541      70  0.000594  0.023197  12.939002
[2.0, 3.0)    440       1  0.000012  0.005348   0.227273
[3.0, 4.0)    754      28  0.000080  0.015786   3.713528
[4.0, 5.0)    440       0  0.000000  0.000000   0.000000
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)     88       0  0.000000  0.000000   0.000000
[7.0, 8.0)    132       0  0.000000  0.000000   0.000000
[8.0, 9.0)    220       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)   88       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__7_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   88       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   138      25  0.002614  0.049420  18.115942
[0.0, 1.0)    442       9  0.000092  0.018895   2.036199
[1.0, 2.0)    408      60  0.000764  0.023197  14.705882
[2.0, 3.0)    665      37  0.000102  0.015786   5.563910
[3.0, 4.0)    750       2  0.000009  0.005348   0.266667
[4.0, 5.0)    308       0  0.000000  0.000000   0.000000
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)    264       0  0.000000  0.000000   0.000000
[7.0, 8.0)    132       0  0.000000  0.000000   0.000000
[8.0, 9.0)    220       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__8_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   44       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   193      68  0.003250  0.049420  35.233161
[0.0, 1.0)    132       0  0.000000  0.000000   0.000000
[1.0, 2.0)    529      17  0.000094  0.018895   3.213611
[2.0, 3.0)    535      46  0.000168  0.015786   8.598131
[3.0, 4.0)    484       1  0.000042  0.020128   0.206612
[4.0, 5.0)    308       0  0.000000  0.000000   0.000000
[5.0, 6.0)    440       0  0.000000  0.000000   0.000000
[6.0, 7.0)    354       1  0.000005  0.001653   0.282486
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    132       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__9_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    94      25  0.003838  0.049420  26.595745
[0.0, 1.0)    314      36  0.000315  0.018895  11.464968
[1.0, 2.0)    485      11  0.000031  0.005348   2.268041
[2.0, 3.0)    355      18  0.000074  0.003791   5.070423
[3.0, 4.0)    176       0  0.000000  0.000000   0.000000
[4.0, 5.0)    528       1  0.000038  0.020128   0.189394
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    266       1  0.000006  0.001653   0.375940
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  308       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__10_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)    44       0  0.000000  0.000000   0.000000
[0.0, 1.0)    283      97  0.002542  0.049420  34.275618
[1.0, 2.0)    355      15  0.000044  0.003999   4.225352
[2.0, 3.0)    399      18  0.000065  0.003791   4.511278
[3.0, 4.0)    220       1  0.000024  0.005348   0.454545
[4.0, 5.0)    486       2  0.000045  0.020128   0.411523
[5.0, 6.0)    352       0  0.000000  0.000000   0.000000
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    352       0  0.000000  0.000000   0.000000
[8.0, 9.0)    440       0  0.000000  0.000000   0.000000
[9.0, 10.0)   308       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__11_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)    50      25  0.007215  0.049420  50.000000
[0.0, 1.0)    180      27  0.000324  0.015786  15.000000
[1.0, 2.0)    229      48  0.001333  0.023197  20.960699
[2.0, 3.0)    266       2  0.000003  0.000524   0.751880
[3.0, 4.0)    268      29  0.000154  0.005348  10.820896
[4.0, 5.0)    220       0  0.000000  0.000000   0.000000
[5.0, 6.0)    660       1  0.000030  0.020128   0.151515
[6.0, 7.0)    354       1  0.000005  0.001653   0.282486
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    484       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)  220       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   88       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__12_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)   103      66  0.006080  0.049420  64.077670
[0.0, 1.0)     92      27  0.000635  0.015786  29.347826
[1.0, 2.0)    176       7  0.000226  0.018895   3.977273
[2.0, 3.0)    220       0  0.000000  0.000000   0.000000
[3.0, 4.0)    402      30  0.000092  0.003791   7.462687
[4.0, 5.0)    220       1  0.000024  0.005348   0.454545
[5.0, 6.0)    484       0  0.000000  0.000000   0.000000
[6.0, 7.0)    398       2  0.000055  0.020128   0.502513
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    440       0  0.000000  0.000000   0.000000
[9.0, 10.0)   308       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  308       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)  132       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__13_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    44       4  0.000790  0.018895   9.090909
[0.0, 1.0)    138      25  0.002614  0.049420  18.115942
[1.0, 2.0)     92      27  0.000635  0.015786  29.347826
[2.0, 3.0)    176       3  0.000028  0.003999   1.704545
[3.0, 4.0)    534      30  0.000069  0.003791   5.617978
[4.0, 5.0)    264       1  0.000020  0.005348   0.378788
[5.0, 6.0)    440       1  0.000046  0.020128   0.227273
[6.0, 7.0)    266       1  0.000006  0.001653   0.375940
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    396       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)  352       0  0.000000  0.000000   0.000000
[11.0, 12.0)  396       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)  220       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__14_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[0.0, 1.0)     44       0  0.000000  0.000000   0.000000
[1.0, 2.0)    270      32  0.001483  0.049420  11.851852
[2.0, 3.0)    225      37  0.000303  0.015786  16.444444
[3.0, 4.0)    401      21  0.000081  0.005348   5.236908
[4.0, 5.0)    264       0  0.000000  0.000000   0.000000
[5.0, 6.0)    442       2  0.000049  0.020128   0.452489
[6.0, 7.0)    440       0  0.000000  0.000000   0.000000
[7.0, 8.0)    352       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)  440       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  308       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)  308       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)  132       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__15_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   53      41  0.005010  0.023197  77.358491
[0.0, 1.0)    226      25  0.001596  0.049420  11.061947
[1.0, 2.0)    132       4  0.000263  0.018895   3.030303
[2.0, 3.0)    139      48  0.000644  0.015786  34.532374
[3.0, 4.0)    487      12  0.000022  0.002210   2.464066
[4.0, 5.0)    308       2  0.000083  0.020128   0.649351
[5.0, 6.0)    486       1  0.000003  0.001653   0.205761
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   396       0  0.000000  0.000000   0.000000
[10.0, 11.0)  396       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)  264       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[15.0, 16.0)  176       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__16_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[0.0, 1.0)     88       0  0.000000  0.000000   0.000000
[1.0, 2.0)    223      18  0.000117  0.003791   8.071749
[2.0, 3.0)    318      59  0.001443  0.049420  18.553459
[3.0, 4.0)    399      13  0.000040  0.005348   3.258145
[4.0, 5.0)    398       1  0.000004  0.001653   0.251256
[5.0, 6.0)    484       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       1  0.000051  0.020128   0.252525
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    220       0  0.000000  0.000000   0.000000
[9.0, 10.0)   308       0  0.000000  0.000000   0.000000
[10.0, 11.0)  352       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)  220       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__17_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[0.0, 1.0)    176       4  0.000198  0.018895   2.272727
[1.0, 2.0)    315      48  0.000284  0.015786  15.238095
[2.0, 3.0)    272      27  0.001330  0.049420   9.926471
[3.0, 4.0)    573      11  0.000026  0.005348   1.919721
[4.0, 5.0)    396       0  0.000000  0.000000   0.000000
[5.0, 6.0)    266       1  0.000006  0.001653   0.375940
[6.0, 7.0)    440       1  0.000046  0.020128   0.227273
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  352       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__18_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[0.0, 1.0)    225      20  0.000120  0.003791   8.888889
[1.0, 2.0)    312      31  0.000299  0.018895   9.935897
[2.0, 3.0)    490      29  0.000757  0.049420   5.918367
[3.0, 4.0)    529      11  0.000056  0.020128   2.079395
[4.0, 5.0)    354       1  0.000005  0.001653   0.282486
[5.0, 6.0)    352       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  396       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__19_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)   101      68  0.003207  0.023197  67.326733
[0.0, 1.0)    310       6  0.000115  0.018895   1.935484
[1.0, 2.0)    311      22  0.000165  0.020128   7.073955
[2.0, 3.0)    622      25  0.000580  0.049420   4.019293
[3.0, 4.0)    441      11  0.000034  0.005348   2.494331
[4.0, 5.0)    442       1  0.000004  0.001653   0.226244
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    352       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__20_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)   145      68  0.002234  0.023197  46.896552
[0.0, 1.0)    132       4  0.000263  0.018895   3.030303
[1.0, 2.0)    579      25  0.000093  0.020128   4.317789
[2.0, 3.0)    579      35  0.000640  0.049420   6.044905
[3.0, 4.0)    660       1  0.000008  0.005348   0.151515
[4.0, 5.0)    484       0  0.000000  0.000000   0.000000
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    132       0  0.000000  0.000000   0.000000
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    440       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)   44       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__21_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    92      27  0.000635  0.015786  29.347826
[0.0, 1.0)    222       6  0.000161  0.018895   2.702703
[1.0, 2.0)    581      47  0.000709  0.049420   8.089501
[2.0, 3.0)    573      11  0.000026  0.005348   1.919721
[3.0, 4.0)    794       1  0.000002  0.001653   0.125945
[4.0, 5.0)    352       0  0.000000  0.000000   0.000000
[5.0, 6.0)    220       0  0.000000  0.000000   0.000000
[6.0, 7.0)    176       0  0.000000  0.000000   0.000000
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    396       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)   88       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__22_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)   186      56  0.002440  0.049420  30.107527
[0.0, 1.0)    354       5  0.000017  0.003999   1.412429
[1.0, 2.0)    442       1  0.000004  0.001653   0.226244
[2.0, 3.0)    356      30  0.000172  0.020128   8.426966
[3.0, 4.0)    748       0  0.000000  0.000000   0.000000
[4.0, 5.0)    440       0  0.000000  0.000000   0.000000
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    264       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)    88       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__23_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)  101      68  0.003207  0.023197  67.326733
[-1.0, 0.0)   138      29  0.002866  0.049420  21.014493
[0.0, 1.0)    310       5  0.000019  0.003999   1.612903
[1.0, 2.0)    529      10  0.000018  0.002210   1.890359
[2.0, 3.0)    354       2  0.000020  0.005348   0.564972
[3.0, 4.0)    839      19  0.000055  0.020128   2.264601
[4.0, 5.0)    352       0  0.000000  0.000000   0.000000
[5.0, 6.0)    308       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    396       0  0.000000  0.000000   0.000000
[9.0, 10.0)    88       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000

--- 糸魚川_気温_℃__0_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   44       1  0.000457  0.020128   2.272727
[-2.0, -1.0)   94      25  0.003838  0.049420  26.595745
[-1.0, 0.0)   136       3  0.000019  0.001653   2.205882
[0.0, 1.0)    264       0  0.000000  0.000000   0.000000
[1.0, 2.0)    540      66  0.000614  0.023197  12.222222
[2.0, 3.0)    396       1  0.000014  0.005348   0.252525
[3.0, 4.0)    837      10  0.000012  0.002210   1.194743
[4.0, 5.0)    308       0  0.000000  0.000000   0.000000
[5.0, 6.0)    576      27  0.000101  0.015786   4.687500
[6.0, 7.0)    176       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)   44       0  0.000000  0.000000   0.000000
[11.0, 12.0)   88       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__1_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-1.0, 0.0)   178       2  0.000005  0.000524   1.123596
[0.0, 1.0)    132       1  0.000152  0.020128   0.757576
[1.0, 2.0)    485      17  0.000102  0.018895   3.505155
[2.0, 3.0)    630      60  0.000466  0.023197   9.523810
[3.0, 4.0)    572       1  0.000009  0.005348   0.174825
[4.0, 5.0)    488      27  0.000120  0.015786   5.532787
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    440       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)  132       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__2_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   94      25  0.003838  0.049420  26.595745
[-1.0, 0.0)    88       0  0.000000  0.000000   0.000000
[0.0, 1.0)    223      13  0.000138  0.020128   5.829596
[1.0, 2.0)    575      25  0.000115  0.018895   4.347826
[2.0, 3.0)    495      42  0.000540  0.023197   8.484848
[3.0, 4.0)    488      28  0.000131  0.015786   5.737705
[4.0, 5.0)    572       0  0.000000  0.000000   0.000000
[5.0, 6.0)    220       0  0.000000  0.000000   0.000000
[6.0, 7.0)    528       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__3_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   88       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   138      25  0.002614  0.049420  18.115942
[0.0, 1.0)    270      35  0.000340  0.020128  12.962963
[1.0, 2.0)    440       3  0.000011  0.003999   0.681818
[2.0, 3.0)    581      41  0.000457  0.023197   7.056799
[3.0, 4.0)    576      28  0.000111  0.015786   4.861111
[4.0, 5.0)    398       1  0.000004  0.001653   0.251256
[5.0, 6.0)    484       0  0.000000  0.000000   0.000000
[6.0, 7.0)    176       0  0.000000  0.000000   0.000000
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)   88       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__4_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   44       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   134       2  0.000007  0.000524   1.492537
[0.0, 1.0)    368      84  0.001891  0.049420  22.826087
[1.0, 2.0)    663      18  0.000039  0.003791   2.714932
[2.0, 3.0)    396       0  0.000000  0.000000   0.000000
[3.0, 4.0)    488      28  0.000131  0.015786   5.737705
[4.0, 5.0)    528       0  0.000000  0.000000   0.000000
[5.0, 6.0)    486       1  0.000003  0.001653   0.205761
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__5_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   88       0  0.000000  0.000000   0.000000
[-1.0, 0.0)    90       2  0.000010  0.000524   2.222222
[0.0, 1.0)    414      91  0.001672  0.049420  21.980676
[1.0, 2.0)    709      38  0.000125  0.020128   5.359661
[2.0, 3.0)    396       1  0.000014  0.005348   0.252525
[3.0, 4.0)    572       0  0.000000  0.000000   0.000000
[4.0, 5.0)    486       1  0.000003  0.001653   0.205761
[5.0, 6.0)    352       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)     88       0  0.000000  0.000000   0.000000
[8.0, 9.0)    176       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)   44       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__6_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   88       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   235      70  0.002813  0.049420  29.787234
[0.0, 1.0)    269      20  0.000101  0.003791   7.434944
[1.0, 2.0)    665      41  0.000140  0.020128   6.165414
[2.0, 3.0)    572       0  0.000000  0.000000   0.000000
[3.0, 4.0)    572       1  0.000009  0.005348   0.174825
[4.0, 5.0)    220       0  0.000000  0.000000   0.000000
[5.0, 6.0)    530       1  0.000003  0.001653   0.188679
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__7_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-2.0, -1.0)   44       0  0.000000  0.000000   0.000000
[-1.0, 0.0)   138      25  0.002614  0.049420  18.115942
[0.0, 1.0)    319      50  0.000960  0.023197  15.673981
[1.0, 2.0)    623      45  0.000136  0.015786   7.223114
[2.0, 3.0)    793      11  0.000038  0.020128   1.387137
[3.0, 4.0)    352       1  0.000015  0.005348   0.284091
[4.0, 5.0)    354       1  0.000005  0.001653   0.282486
[5.0, 6.0)    528       0  0.000000  0.000000   0.000000
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)   88       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)   44       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__8_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)   228      31  0.001739  0.049420  13.596491
[0.0, 1.0)    280      89  0.001268  0.023197  31.785714
[1.0, 2.0)    396       0  0.000000  0.000000   0.000000
[2.0, 3.0)    484       0  0.000000  0.000000   0.000000
[3.0, 4.0)    529      12  0.000067  0.020128   2.268431
[4.0, 5.0)    396       0  0.000000  0.000000   0.000000
[5.0, 6.0)    264       0  0.000000  0.000000   0.000000
[6.0, 7.0)    706       1  0.000002  0.001653   0.141643
[7.0, 8.0)    132       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__9_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)    53      41  0.005010  0.023197  77.358491
[0.0, 1.0)    317      54  0.000395  0.018895  17.034700
[1.0, 2.0)    314      25  0.001149  0.049420   7.961783
[2.0, 3.0)    440       1  0.000012  0.005348   0.227273
[3.0, 4.0)    309      10  0.000032  0.002210   3.236246
[4.0, 5.0)    264       1  0.000076  0.020128   0.378788
[5.0, 6.0)    662       1  0.000002  0.001653   0.151057
[6.0, 7.0)    484       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__10_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[0.0, 1.0)    277      71  0.001187  0.023197  25.631769
[1.0, 2.0)    273      47  0.001544  0.049420  17.216117
[2.0, 3.0)    355      13  0.000045  0.005348   3.661972
[3.0, 4.0)    222       1  0.000007  0.001653   0.450450
[4.0, 5.0)    352       1  0.000057  0.020128   0.284091
[5.0, 6.0)    484       0  0.000000  0.000000   0.000000
[6.0, 7.0)    484       0  0.000000  0.000000   0.000000
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  352       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[16.0, 17.0)  132       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__11_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[0.0, 1.0)    141      44  0.001919  0.023197  31.205674
[1.0, 2.0)    359      49  0.000332  0.018895  13.649025
[2.0, 3.0)     50      25  0.007215  0.049420  50.000000
[3.0, 4.0)    311      11  0.000037  0.002210   3.536977
[4.0, 5.0)    442       4  0.000060  0.020128   0.904977
[5.0, 6.0)    396       0  0.000000  0.000000   0.000000
[6.0, 7.0)    352       0  0.000000  0.000000   0.000000
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   308       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  176       0  0.000000  0.000000   0.000000
[12.0, 13.0)  264       0  0.000000  0.000000   0.000000
[13.0, 14.0)  264       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)  220       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000
[22.0, 23.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__12_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)    53      41  0.005010  0.023197  77.358491
[0.0, 1.0)     88       3  0.000057  0.003999   3.409091
[1.0, 2.0)    180      27  0.000324  0.015786  15.000000
[2.0, 3.0)    229      47  0.001841  0.049420  20.524017
[3.0, 4.0)    220       1  0.000091  0.020128   0.454545
[4.0, 5.0)    311      11  0.000037  0.002210   3.536977
[5.0, 6.0)    486       3  0.000013  0.005348   0.617284
[6.0, 7.0)    220       0  0.000000  0.000000   0.000000
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   308       0  0.000000  0.000000   0.000000
[10.0, 11.0)  308       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  308       0  0.000000  0.000000   0.000000
[13.0, 14.0)  264       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[15.0, 16.0)  264       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__13_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[0.0, 1.0)     53      41  0.005010  0.023197  77.358491
[1.0, 2.0)    180      30  0.000352  0.015786  16.666667
[2.0, 3.0)    176       4  0.000198  0.018895   2.272727
[3.0, 4.0)    270      25  0.001336  0.049420   9.259259
[4.0, 5.0)    268      29  0.000209  0.020128  10.820896
[5.0, 6.0)    398       2  0.000002  0.000524   0.502513
[6.0, 7.0)    530       2  0.000013  0.005348   0.377358
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  440       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)  220       0  0.000000  0.000000   0.000000
[14.0, 15.0)  264       0  0.000000  0.000000   0.000000
[15.0, 16.0)  264       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000
[22.0, 23.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__14_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[0.0, 1.0)     44       0  0.000000  0.000000   0.000000
[1.0, 2.0)    233      72  0.001540  0.023197  30.901288
[2.0, 3.0)    176       3  0.000028  0.003999   1.704545
[3.0, 4.0)    229      43  0.001689  0.049420  18.777293
[4.0, 5.0)    309      10  0.000032  0.002210   3.236246
[5.0, 6.0)    268       4  0.000085  0.020128   1.492537
[6.0, 7.0)    572       1  0.000009  0.005348   0.174825
[7.0, 8.0)    308       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   396       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)  264       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)  396       0  0.000000  0.000000   0.000000
[15.0, 16.0)  220       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000
[19.0, 20.0)   88       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__15_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[0.0, 1.0)     97      41  0.002738  0.023197  42.268041
[1.0, 2.0)    186      52  0.002253  0.049420  27.956989
[2.0, 3.0)     88       0  0.000000  0.000000   0.000000
[3.0, 4.0)    355      25  0.000186  0.018895   7.042254
[4.0, 5.0)    265      10  0.000037  0.002210   3.773585
[5.0, 6.0)    180       3  0.000014  0.001653   1.666667
[6.0, 7.0)    572       2  0.000045  0.020128   0.349650
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    440       0  0.000000  0.000000   0.000000
[9.0, 10.0)   308       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[14.0, 15.0)  484       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)  132       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__16_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[0.0, 1.0)    141      45  0.002130  0.023197  31.914894
[1.0, 2.0)    186      52  0.002253  0.049420  27.956989
[2.0, 3.0)    267      21  0.000116  0.003999   7.865169
[3.0, 4.0)    176       0  0.000000  0.000000   0.000000
[4.0, 5.0)    267      12  0.000040  0.002210   4.494382
[5.0, 6.0)    398       2  0.000018  0.005348   0.502513
[6.0, 7.0)    308       1  0.000065  0.020128   0.324675
[7.0, 8.0)    660       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)  308       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)  528       0  0.000000  0.000000   0.000000
[15.0, 16.0)  132       0  0.000000  0.000000   0.000000
[16.0, 17.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000
[18.0, 19.0)   88       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[22.0, 23.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__17_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[0.0, 1.0)    189      68  0.001714  0.023197  35.978836
[1.0, 2.0)    270      29  0.001465  0.049420  10.740741
[2.0, 3.0)    176       3  0.000028  0.003999   1.704545
[3.0, 4.0)    267      18  0.000098  0.003791   6.741573
[4.0, 5.0)    401      13  0.000031  0.002210   3.241895
[5.0, 6.0)    264       1  0.000020  0.005348   0.378788
[6.0, 7.0)    616       1  0.000033  0.020128   0.162338
[7.0, 8.0)    440       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)  308       0  0.000000  0.000000   0.000000
[12.0, 13.0)  132       0  0.000000  0.000000   0.000000
[13.0, 14.0)  220       0  0.000000  0.000000   0.000000
[14.0, 15.0)  352       0  0.000000  0.000000   0.000000
[15.0, 16.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)  132       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[22.0, 23.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__18_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-1.0, 0.0)   101      68  0.003207  0.023197  67.326733
[0.0, 1.0)     94      25  0.003838  0.049420  26.595745
[1.0, 2.0)    264       7  0.000151  0.018895   2.651515
[2.0, 3.0)    222       1  0.000007  0.001653   0.450450
[3.0, 4.0)    268      28  0.000134  0.003791  10.447761
[4.0, 5.0)    398       3  0.000016  0.005348   0.753769
[5.0, 6.0)    352       1  0.000057  0.020128   0.284091
[6.0, 7.0)    924       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    220       0  0.000000  0.000000   0.000000
[9.0, 10.0)   176       0  0.000000  0.000000   0.000000
[10.0, 11.0)  352       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)   88       0  0.000000  0.000000   0.000000
[13.0, 14.0)  396       0  0.000000  0.000000   0.000000
[14.0, 15.0)  176       0  0.000000  0.000000   0.000000
[16.0, 17.0)   88       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[22.0, 23.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__19_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-3.0, -2.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    44       0  0.000000  0.000000   0.000000
[0.0, 1.0)     98      52  0.004277  0.049420  53.061224
[1.0, 2.0)    264       7  0.000151  0.018895   2.651515
[2.0, 3.0)    448      31  0.000086  0.003791   6.919643
[3.0, 4.0)    308       0  0.000000  0.000000   0.000000
[4.0, 5.0)    132       1  0.000041  0.005348   0.757576
[5.0, 6.0)    792       1  0.000025  0.020128   0.126263
[6.0, 7.0)    616       0  0.000000  0.000000   0.000000
[7.0, 8.0)    132       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  352       0  0.000000  0.000000   0.000000
[13.0, 14.0)  176       0  0.000000  0.000000   0.000000
[14.0, 15.0)   44       0  0.000000  0.000000   0.000000
[15.0, 16.0)   88       0  0.000000  0.000000   0.000000
[20.0, 21.0)   44       0  0.000000  0.000000   0.000000
[21.0, 22.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__20_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    44       0  0.000000  0.000000   0.000000
[0.0, 1.0)    182      28  0.002009  0.049420  15.384615
[1.0, 2.0)    402      32  0.000236  0.018895   7.960199
[2.0, 3.0)    224      28  0.000160  0.003791  12.500000
[3.0, 4.0)    310       3  0.000020  0.005348   0.967742
[4.0, 5.0)    440       0  0.000000  0.000000   0.000000
[5.0, 6.0)    748       1  0.000027  0.020128   0.133690
[6.0, 7.0)    308       0  0.000000  0.000000   0.000000
[7.0, 8.0)    396       0  0.000000  0.000000   0.000000
[8.0, 9.0)    264       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)  264       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[14.0, 15.0)  132       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__21_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    92      27  0.000635  0.015786  29.347826
[0.0, 1.0)    226      28  0.001618  0.049420  12.389381
[1.0, 2.0)    310       5  0.000117  0.018895   1.612903
[2.0, 3.0)    358      31  0.000118  0.005348   8.659218
[3.0, 4.0)    264       0  0.000000  0.000000   0.000000
[4.0, 5.0)    704       1  0.000029  0.020128   0.142045
[5.0, 6.0)    484       0  0.000000  0.000000   0.000000
[6.0, 7.0)    396       0  0.000000  0.000000   0.000000
[7.0, 8.0)    176       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  220       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[14.0, 15.0)   88       0  0.000000  0.000000   0.000000
[19.0, 20.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__22_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    44       0  0.000000  0.000000   0.000000
[0.0, 1.0)    232      56  0.001835  0.049420  24.137931
[1.0, 2.0)    531      16  0.000086  0.018895   3.013183
[2.0, 3.0)    264       1  0.000020  0.005348   0.378788
[3.0, 4.0)    531      18  0.000049  0.003791   3.389831
[4.0, 5.0)    572       1  0.000035  0.020128   0.174825
[5.0, 6.0)    484       0  0.000000  0.000000   0.000000
[6.0, 7.0)    176       0  0.000000  0.000000   0.000000
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    352       0  0.000000  0.000000   0.000000
[9.0, 10.0)   264       0  0.000000  0.000000   0.000000
[10.0, 11.0)  352       0  0.000000  0.000000   0.000000
[11.0, 12.0)   44       0  0.000000  0.000000   0.000000
[12.0, 13.0)  264       0  0.000000  0.000000   0.000000
[13.0, 14.0)  132       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__23_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   53      41  0.005010  0.023197  77.358491
[-1.0, 0.0)    88       0  0.000000  0.000000   0.000000
[0.0, 1.0)    274      59  0.001675  0.049420  21.532847
[1.0, 2.0)    443      11  0.000026  0.002210   2.483070
[2.0, 3.0)    310       3  0.000020  0.005348   0.967742
[3.0, 4.0)    619      18  0.000042  0.003791   2.907916
[4.0, 5.0)    572       0  0.000000  0.000000   0.000000
[5.0, 6.0)    352       1  0.000057  0.020128   0.284091
[6.0, 7.0)    352       0  0.000000  0.000000   0.000000
[7.0, 8.0)    220       0  0.000000  0.000000   0.000000
[8.0, 9.0)    308       0  0.000000  0.000000   0.000000
[9.0, 10.0)   352       0  0.000000  0.000000   0.000000
[10.0, 11.0)  176       0  0.000000  0.000000   0.000000
[11.0, 12.0)  132       0  0.000000  0.000000   0.000000
[12.0, 13.0)  220       0  0.000000  0.000000   0.000000
[13.0, 14.0)   88       0  0.000000  0.000000   0.000000
[18.0, 19.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_気温_℃__0_00 ---

               件数  着雪発生件数     平均着雪量     最大着雪量      着雪発生率
気温帯
[-4.0, -3.0)   50      25  0.007215  0.049420  50.000000
[-1.0, 0.0)   132       0  0.000000  0.000000   0.000000
[0.0, 1.0)    266       7  0.000210  0.020128   2.631579
[1.0, 2.0)    362      54  0.000774  0.023197  14.917127
[2.0, 3.0)    443      18  0.000059  0.003791   4.063205
[3.0, 4.0)    662       2  0.000011  0.005348   0.302115
[4.0, 5.0)    484       0  0.000000  0.000000   0.000000
[5.0, 6.0)    352       0  0.000000  0.000000   0.000000
[6.0, 7.0)    444      27  0.000132  0.015786   6.081081
[7.0, 8.0)    264       0  0.000000  0.000000   0.000000
[8.0, 9.0)    396       0  0.000000  0.000000   0.000000
[9.0, 10.0)   220       0  0.000000  0.000000   0.000000
[10.0, 11.0)   44       0  0.000000  0.000000   0.000000
[11.0, 12.0)  220       0  0.000000  0.000000   0.000000
[12.0, 13.0)  176       0  0.000000  0.000000   0.000000
[13.0, 14.0)   44       0  0.000000  0.000000   0.000000
[17.0, 18.0)   44       0  0.000000  0.000000   0.000000

--- 金沢_列車通過時_気温 ---

               件数  着雪発生件数     平均着雪量     最大着雪量       着雪発生率
気温帯
[-4.0, -3.0)    5       5  0.006110  0.014888  100.000000
[-3.0, -2.0)    3       1  0.000842  0.002526   33.333333
[-2.0, -1.0)   11       0  0.000000  0.000000    0.000000
[-1.0, 0.0)    67      25  0.003872  0.037332   37.313433
[0.0, 1.0)    180      36  0.000762  0.011760   20.000000
[1.0, 2.0)    334      26  0.000504  0.049420    7.784431
[2.0, 3.0)    359      13  0.000035  0.001921    3.621170
[3.0, 4.0)    309       8  0.000046  0.005348    2.588997
[4.0, 5.0)    340       1  0.000004  0.001195    0.294118
[5.0, 6.0)    466       0  0.000000  0.000000    0.000000
[6.0, 7.0)    453       0  0.000000  0.000000    0.000000
[7.0, 8.0)    323       0  0.000000  0.000000    0.000000
[8.0, 9.0)    303       0  0.000000  0.000000    0.000000
[9.0, 10.0)   280       0  0.000000  0.000000    0.000000
[10.0, 11.0)  239       0  0.000000  0.000000    0.000000
[11.0, 12.0)  187       0  0.000000  0.000000    0.000000
[12.0, 13.0)  169       0  0.000000  0.000000    0.000000
[13.0, 14.0)  131       0  0.000000  0.000000    0.000000
[14.0, 15.0)  168       0  0.000000  0.000000    0.000000
[15.0, 16.0)   81       0  0.000000  0.000000    0.000000
[16.0, 17.0)   49       0  0.000000  0.000000    0.000000
[17.0, 18.0)   38       0  0.000000  0.000000    0.000000
[18.0, 19.0)   20       0  0.000000  0.000000    0.000000
[19.0, 20.0)   14       0  0.000000  0.000000    0.000000
[20.0, 21.0)   20       0  0.000000  0.000000    0.000000
[21.0, 22.0)   13       0  0.000000  0.000000    0.000000
[22.0, 23.0)   15       0  0.000000  0.000000    0.000000

--- 新高岡_列車通過時_気温 ---

ValueError: arange: cannot compute length